security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        database:
            entity:
                class: App\Modules\Security\Persistence\Doctrine\Entity\User
                manager_name: security
                property: email
        jwt:
            lexik_jwt:
                class: App\Infrastructure\Security\LoggedInUser
    firewalls:
        login:
            pattern: ^/api/login
            provider: database
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api/admin
            provider: jwt
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/admin, roles: IS_AUTHENTICATED_FULLY }
