version: '3.7'
services:
  &smf-api smf-api:
    image: nginx:stable-alpine
    hostname: *smf-api
    volumes:
      - ./:/app
      - ./docker/dev/config/nginx/snippets:/etc/nginx/snippets
      - ./docker/dev/config/nginx/backend/backend.conf:/etc/nginx/conf.d/default.conf
      - ./docker/dev/config/nginx/backend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - smf-php-fpm
    ports:
      - "8081:80"
    working_dir: /app

  &smf-fpm smf-php-fpm:
    image: sd2020/php81-fpm-alpine
    hostname: *smf-fpm
    tty: true
    volumes:
      - ./:/app
      - ./docker/dev/config/user/.bashrc:/root/.bashrc
      - ./docker/dev/config/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/dev/config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    working_dir: /app

  &smf-cli smf-php-cli:
    image: sd2020/php81-cli-dev-alpine
    hostname: *smf-cli
    tty: true
    volumes:
      - ./:/app
      - ./docker/dev/config/user/.bashrc:/root/.bashrc
      - composer:/root/.composer/cache
    working_dir: /app

volumes:
  composer:
