
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true #

    App\Infrastructure\Events\Api\ApplicationEventPublisher:
        class: App\Infrastructure\Events\Api\ApplicationEventPublisher